framework:
    annotations:
        cache: oro.cache.annotations

doctrine:
    orm:
        metadata_cache_driver: redis
        query_cache_driver: redis
        result_cache_driver: redis

jms_serializer:
    metadata:
        cache: Metadata\Cache\DoctrineCacheAdapter

#security:
#    firewalls:
#        wsse_secured:
#            wsse:
#                nonce_cache_service_id: oro.cache.wsse_nonces

#monolog:
#    handlers:
#        main:
#            type: service
#            id: snc_redis.monolog.handler
#            level: debug

swiftmailer:
    spool:
        type: service
        id: snc_redis.swiftmailer.spool
    # spool:
    #     type: redis

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://%redis_password%@%redis_host%:%redis_port%/1
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: redis://%redis_password%@%redis_host%:%redis_port%/2
        session:
            type: phpredis
            alias: session
            dsn: redis://%redis_password%@%redis_host%:%redis_port%/3
#        monolog:
#            type: phpredis
#            alias: monolog
#            dsn: redis://%redis_host%/4
#            logging: false
#            options:
#                connection_persistent: true
        swiftmailer:
            type: phpredis
            alias: swiftmailer
            dsn: redis://%redis_password%@%redis_host%:%redis_port%/5
            logging: %kernel.debug%
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: [default, config, search]
        result_cache:
            client: doctrine
            entity_manager: [default, config, search]
        query_cache:
            client: doctrine
            entity_manager: [default, config, search]
    session:
        client: session
        prefix: session
        use_as_default: true
#    monolog:
#        client: monolog
#        key: monolog
    swiftmailer:
        client: default
        key: swiftmailer
